// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO33vwYZjkl0FScFk-ubIIn0Q17HIZVa8',
    appId: '1:506862252397:ios:6ab0ea250db813555aaa64',
    messagingSenderId: '506862252397',
    projectId: 'hastane-kod-uygulamas',
    storageBucket: 'hastane-kod-uygulamas.firebasestorage.app',
    iosBundleId: 'com.example.hospitalCodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV2NsioKX36T3sULRLq0XANEWhbM5sO3w',
    appId: '1:506862252397:web:0cdc4c3730218dad5aaa64',
    messagingSenderId: '506862252397',
    projectId: 'hastane-kod-uygulamas',
    authDomain: 'hastane-kod-uygulamas.firebaseapp.com',
    storageBucket: 'hastane-kod-uygulamas.firebasestorage.app',
    measurementId: 'G-5CJY0GZ01S',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV2NsioKX36T3sULRLq0XANEWhbM5sO3w',
    appId: '1:506862252397:web:0cdc4c3730218dad5aaa64',
    messagingSenderId: '506862252397',
    projectId: 'hastane-kod-uygulamas',
    authDomain: 'hastane-kod-uygulamas.firebaseapp.com',
    storageBucket: 'hastane-kod-uygulamas.firebasestorage.app',
    measurementId: 'G-5CJY0GZ01S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO33vwYZjkl0FScFk-ubIIn0Q17HIZVa8',
    appId: '1:506862252397:ios:6ab0ea250db813555aaa64',
    messagingSenderId: '506862252397',
    projectId: 'hastane-kod-uygulamas',
    storageBucket: 'hastane-kod-uygulamas.firebasestorage.app',
    iosBundleId: 'com.example.hospitalCodeApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-qUDohCeaLNJxuPOGflltYVa15huYlA',
    appId: '1:506862252397:android:5f120bd2c6ce81125aaa64',
    messagingSenderId: '506862252397',
    projectId: 'hastane-kod-uygulamas',
    storageBucket: 'hastane-kod-uygulamas.firebasestorage.app',
  );

}